(defun add-subdirs-to-load-path (dir)
  "Recursive add dirs to `load-path`."
  (let ((default-directory (file-name-as-directory dir)))
    (add-to-list 'load-path dir)
    (normal-top-level-add-subdirs-to-load-path)))

(add-subdirs-to-load-path "~/.emacs.d/site-lisp/")

(require 'init-const)
(require 'init-custom)
(require 'init-package)
(require 'init-base)
(require 'init-dashboard)

;; (require 'init-xah-fly-keys)
(require 'init-thing-edit)
(require 'init-projectile)
(require 'init-ui)
(require 'init-v)

(require 'init-yasnippet)
(require 'init-awesome-pair)
(require 'init-elisp)
(require 'init-company)
(require 'init-go)
(require 'init-lsp)
(require 'init-highlight)
(require 'init-ivy)
(require 'init-prog)
(require 'init-magit)
(require 'init-trans)
(require 'init-web)
(require 'init-snails)
(require 'init-scala)
(require 'init-protobuf)
(require 'init-docker)
(require 'init-org)
(require 'init-tools)
(require 'init-flycheck)

(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)
